Update Mac

diff --git a/Mac b/Mac
--- a/Mac
+++ b/Mac
@@ -14,8 +14,8 @@ MP_CONFIG_INT="mesh_retry_timeout mesh_confirm_timeout mesh_holding_timeout mesh
 MP_CONFIG_BOOL="mesh_auto_open_plinks mesh_fwding"
 MP_CONFIG_STRING="mesh_power_mode"
 
-iw() {
-	command iw $@ || logger -t mac80211 "Failed command: iw $@"
+ifconfig() {
+	command ifconfig $@ || logger -t mac80211 "Failed command: ifconfig $@"
 }
 
 drv_mac80211_init_device_config() {
@@ -153,7 +153,7 @@ mac80211_hostapd_setup_base() {
 			dsss_cck_40:1
 
 		ht_cap_mask=0
-		for cap in $(iw phy "$phy" info | grep 'Capabilities:' | cut -d: -f2); do
+		for cap in $(ifconfig phy "$phy" info | grep 'Capabilities:' | cut -d: -f2); do
 			ht_cap_mask="$(($ht_cap_mask | $cap))"
 		done
 
@@ -236,7 +236,7 @@ mac80211_hostapd_setup_base() {
 		set_default tx_burst 2.0
 		append base_cfg "ieee80211ac=1" "$N"
 		vht_cap=0
-		for cap in $(iw phy "$phy" info | awk -F "[()]" '/VHT Capabilities/ { print $2 }'); do
+		for cap in $(ifconfig phy "$phy" info | awk -F "[()]" '/VHT Capabilities/ { print $2 }'); do
 			vht_cap="$(($vht_cap | $cap))"
 		done
 
@@ -423,21 +423,21 @@ mac80211_check_ap() {
 	has_ap=1
 }
 
-mac80211_iw_interface_add() {
+mac80211_ifconfig_interface_add() {
 	local phy="$1"
 	local ifname="$2"
 	local type="$3"
 	local wdsflag="$4"
 	local rc
 
-	iw phy "$phy" interface add "$ifname" type "$type" $wdsflag
+	ifconfig phy "$phy" interface add "$ifname" type "$type" $wdsflag
 	rc="$?"
 
 	[ "$rc" = 233 ] && {
 		# Device might have just been deleted, give the kernel some time to finish cleaning it up
 		sleep 1
 
-		iw phy "$phy" interface add "$ifname" type "$type" $wdsflag
+		ifconfig phy "$phy" interface add "$ifname" type "$type" $wdsflag
 		rc="$?"
 	}
 
@@ -477,7 +477,7 @@ mac80211_prepare_vif() {
 	# It is far easier to delete and create the desired interface
 	case "$mode" in
 		adhoc)
-			mac80211_iw_interface_add "$phy" "$ifname" adhoc || return
+			mac80211_ifconfig_interface_add "$phy" "$ifname" adhoc || return
 		;;
 		ap)
 			# Hostapd will handle recreating the interface and
@@ -491,29 +491,29 @@ mac80211_prepare_vif() {
 			mac80211_hostapd_setup_bss "$phy" "$ifname" "$macaddr" "$type" || return
 
 			[ -n "$hostapd_ctrl" ] || {
-				mac80211_iw_interface_add "$phy" "$ifname" __ap || return
+				mac80211_ifconfig_interface_add "$phy" "$ifname" __ap || return
 				hostapd_ctrl="${hostapd_ctrl:-/var/run/hostapd/$ifname}"
 			}
 		;;
 		mesh)
-			mac80211_iw_interface_add "$phy" "$ifname" mp || return
+			mac80211_ifconfig_interface_add "$phy" "$ifname" mp || return
 		;;
 		monitor)
-			mac80211_iw_interface_add "$phy" "$ifname" monitor || return
+			mac80211_ifconfig_interface_add "$phy" "$ifname" monitor || return
 		;;
 		sta)
 			local wdsflag=
 			staidx="$(($staidx + 1))"
 			[ "$wds" -gt 0 ] && wdsflag="4addr on"
-			mac80211_iw_interface_add "$phy" "$ifname" managed "$wdsflag" || return
+			mac80211_ifconfig_interface_add "$phy" "$ifname" managed "$wdsflag" || return
 			[ "$powersave" -gt 0 ] && powersave="on" || powersave="off"
-			iw "$ifname" set power_save "$powersave"
+			ifconfig "$ifname" set power_save "$powersave"
 		;;
 	esac
 
 	case "$mode" in
 		monitor|mesh)
-			[ "$auto_channel" -gt 0 ] || iw dev "$ifname" set channel "$channel" $iw_htmode
+			[ "$auto_channel" -gt 0 ] || ifconfig dev "$ifname" set channel "$channel" $ifconfig_htmode
 		;;
 	esac
 
@@ -544,40 +544,40 @@ mac80211_setup_supplicant_noctl() {
 	wpa_supplicant_run "$ifname"
 }
 
-mac80211_prepare_iw_htmode() {
+mac80211_prepare_ifconfig_htmode() {
 	case "$htmode" in
-		VHT20|HT20) iw_htmode=HT20;;
+		VHT20|HT20) ifconfig_htmode=HT20;;
 		HT40*|VHT40|VHT160)
 			case "$hwmode" in
 				a)
 					case "$(( ($channel / 4) % 2 ))" in
-						1) iw_htmode="HT40+" ;;
-						0) iw_htmode="HT40-";;
+						1) ifconfig_htmode="HT40+" ;;
+						0) ifconfig_htmode="HT40-";;
 					esac
 				;;
 				*)
 					case "$htmode" in
-						HT40+) iw_htmode="HT40+";;
-						HT40-) iw_htmode="HT40-";;
+						HT40+) ifconfig_htmode="HT40+";;
+						HT40-) ifconfig_htmode="HT40-";;
 						*)
 							if [ "$channel" -lt 7 ]; then
-								iw_htmode="HT40+"
+								ifconfig_htmode="HT40+"
 							else
-								iw_htmode="HT40-"
+								ifconfig_htmode="HT40-"
 							fi
 						;;
 					esac
 				;;
 			esac
-			[ "$auto_channel" -gt 0 ] && iw_htmode="HT40+"
+			[ "$auto_channel" -gt 0 ] && ifconfig_htmode="HT40+"
 		;;
 		VHT80)
-			iw_htmode="80MHZ"
+			ifconfig_htmode="80MHZ"
 		;;
 		NONE|NOHT)
-			iw_htmode="NOHT"
+			ifconfig_htmode="NOHT"
 		;;
-		*) iw_htmode="" ;;
+		*) ifconfig_htmode="" ;;
 	esac
 
 }
@@ -615,7 +615,7 @@ mac80211_setup_adhoc() {
 	mcval=
 	[ -n "$mcast_rate" ] && wpa_supplicant_add_rate mcval "$mcast_rate"
 
-	iw dev "$ifname" ibss join "$ssid" $freq $iw_htmode fixed-freq $bssid \
+	ifconfig dev "$ifname" ibss join "$ssid" $freq $ifconfig_htmode fixed-freq $bssid \
 		beacon-interval $beacon_int \
 		${brstr:+basic-rates $brstr} \
 		${mcval:+mcast-rate $mcval} \
@@ -629,7 +629,7 @@ mac80211_setup_mesh() {
 	[ -n "$mcast_rate" ] && wpa_supplicant_add_rate mcval "$mcast_rate"
 	[ -n "$mesh_id" ] && ssid="$mesh_id"
 
-	iw dev "$ifname" mesh join "$ssid" freq $freq $iw_htmode \
+	ifconfig dev "$ifname" mesh join "$ssid" freq $freq $ifconfig_htmode \
 		${mcval:+mcast-rate $mcval} \
 		beacon-interval $beacon_int
 }
@@ -653,7 +653,7 @@ mac80211_setup_vif() {
 	}
 
 	set_default vif_txpower "$txpower"
-	[ -z "$vif_txpower" ] || iw dev "$ifname" set txpower fixed "${vif_txpower%%.*}00"
+	[ -z "$vif_txpower" ] || ifconfig dev "$ifname" set txpower fixed "${vif_txpower%%.*}00"
 
 	case "$mode" in
 		mesh)
@@ -666,7 +666,7 @@ mac80211_setup_vif() {
 			fi
 			for var in $MP_CONFIG_INT $MP_CONFIG_BOOL $MP_CONFIG_STRING; do
 				json_get_var mp_val "$var"
-				[ -n "$mp_val" ] && iw dev "$ifname" set mesh_param "$var" "$mp_val"
+				[ -n "$mp_val" ] && ifconfig dev "$ifname" set mesh_param "$var" "$mp_val"
 			done
 		;;
 		adhoc)
@@ -690,13 +690,13 @@ mac80211_setup_vif() {
 get_freq() {
 	local phy="$1"
 	local chan="$2"
-	iw "$phy" info | grep -E -m1 "(\* ${chan:-....} MHz${chan:+|\\[$chan\\]})" | grep MHz | awk '{print $2}'
+	ifconfig "$phy" info | grep -E -m1 "(\* ${chan:-....} MHz${chan:+|\\[$chan\\]})" | grep MHz | awk '{print $2}'
 }
 
 chan_is_dfs() {
 	local phy="$1"
 	local chan="$2"
-	iw "$phy" info | grep -E -m1 "(\* ${chan:-....} MHz${chan:+|\\[$chan\\]})" | grep -q "MHz.*radar detection"
+	ifconfig "$phy" info | grep -E -m1 "(\* ${chan:-....} MHz${chan:+|\\[$chan\\]})" | grep -q "MHz.*radar detection"
 	return $!
 }
 
@@ -705,7 +705,7 @@ mac80211_interface_cleanup() {
 
 	for wdev in $(list_phy_interfaces "$phy"); do
 		ip link set dev "$wdev" down 2>/dev/null
-		iw dev "$wdev" del
+		ifconfig dev "$wdev" del
 	done
 }
 
@@ -741,8 +741,8 @@ drv_mac80211_setup() {
 	[ "$auto_channel" -gt 0 ] || freq="$(get_freq "$phy" "$channel")"
 
 	[ -n "$country" ] && {
-		iw reg get | grep -q "^country $country:" || {
-			iw reg set "$country"
+		ifconfig reg get | grep -q "^country $country:" || {
+			ifconfig reg set "$country"
 			sleep 1
 		}
 	}
@@ -767,12 +767,12 @@ drv_mac80211_setup() {
 	[ "$txantenna" = "all" ] && txantenna=0xffffffff
 	[ "$rxantenna" = "all" ] && rxantenna=0xffffffff
 
-	iw phy "$phy" set antenna $txantenna $rxantenna >/dev/null 2>&1
-	iw phy "$phy" set antenna_gain $antenna_gain
-	iw phy "$phy" set distance "$distance"
+	ifconfig phy "$phy" set antenna $txantenna $rxantenna >/dev/null 2>&1
+	ifconfig phy "$phy" set antenna_gain $antenna_gain
+	ifconfig phy "$phy" set distance "$distance"
 
-	[ -n "$frag" ] && iw phy "$phy" set frag "${frag%%.*}"
-	[ -n "$rts" ] && iw phy "$phy" set rts "${rts%%.*}"
+	[ -n "$frag" ] && ifconfig phy "$phy" set frag "${frag%%.*}"
+	[ -n "$rts" ] && ifconfig phy "$phy" set rts "${rts%%.*}"
 
 	has_ap=
 	hostapd_ctrl=
@@ -784,7 +784,7 @@ drv_mac80211_setup() {
 	for_each_interface "sta adhoc mesh" mac80211_set_noscan
 	[ -n "$has_ap" ] && mac80211_hostapd_setup_base "$phy"
 
-	mac80211_prepare_iw_htmode
+	mac80211_prepare_ifconfig_htmode
 	for_each_interface "sta adhoc mesh monitor" mac80211_prepare_vif
 	for_each_interface "ap" mac80211_prepare_vif
 
@@ -823,3 +823,4 @@ drv_mac80211_teardown() {
 }
 
 add_driver mac80211
+
